### ISSUE TITLE
Out of memmory when using PLS / VIP to ranking the filters 

### ISSUE THREAD

**Issue by purinsat** [arturjordao/PruningNeuralNetworks#3]
Dear @arturjordao,
Now, I can maximum use the picture for PLS Regression for about 4000 pictures (input size is 224x224), more than this my GPU is out of memory.
So, is it possible to make a process that subsampling the input picture for using PLS Regression?

Best regards,
Satthamnuwong Purin

**Comment by arturjordao** [comment]
Dear @PurinSatthamn,

You can reduce the batch size in line 78 of VIPPruning.py. Something like this:
X = self.conv_net.predict(X, batch_size=1)

It worth mentioning that my pruning method is memory-hungry for large datasets. To address this problem, you can use a percentage of data (i.e., 10%) to prune the network (as I mentioned in my papers).

**Comment by purinsat** [comment]
Dear @arturjordao 
I am really new in the machine learning field so, really sorry for asking too many questions.
I am trying to learn things about machine learning.
I already read the paper but the thing is my 10% of data is about 8,000 pictures (all of my training data are 80,000 pictures)
so, I tried to find a way to decrease the memory used when running this code, "X = self.conv_net.predict(X, batch_size=1)".
I understood that using only 10% of data would be good enough for the pruned process reference from your paper. 
So, 
1. Do the "pls_model.fit(X, y)", it's in the fit function in VIPPruning class, support the data generator,?
Would it help to decrease the memory if I using a data generator instead of throwing all the data straight to it?

2. I'm looking forward to using input size 456x456 instead of 224x224. So, the number of pictures that I can use for pls_model.fit(X, y) gonna decreased depends on my memory. Am I understand it correctly? 

3. The model that created by getting the output of the convolutional layer, the custom_model function in VIPPrunning class
if it is bigger, will the memory that used by "self.conv_net.predict" gonna higher, so the number of pictures that can use in  "pls_model.fit(X, y)" need to be decreased too. Am I understand it correctly? 

I am not quite good at the English language too. So, my grammar and sentence may be weird.
I apologize for this thing too.

Best regards 
Satthamnuwong Purin

**Comment by arturjordao** [comment]
Dear @PurinSatthamn 

1. **Do the "pls_model.fit(X, y)", it's in the fit function in VIPPruning class, support the data generator,? 
Would it help to decrease the memory if I using a data generator instead of throwing all the data straight to it?**
No, it does. The traditional PLS does not work on an incremental (i.e., where the data are generated infinitely - data generator) scheme.

2.  **I'm looking forward to using input size 456x456 instead of 224x224. So, the number of pictures that I can use for pls_model.fit(X, y) gonna decreased depends on my memory. Am I understand it correctly?**
Yes, it is correct. It turns out that large feature maps (variable X) require more memory.
Roughly speaking, from 224 to 456 the memory consumption will increase around x2.

3. **The model that created by getting the output of the convolutional layer, the custom_model function in VIPPrunning class
if it is bigger, will the memory that used by "self.conv_net.predict" gonna higher, so the number of pictures that can use in "pls_model.fit(X, y)" need to be decreased too. Am I understand it correctly?**
Yes, it is correct. The reason is your issue 2.

Due to memory-constraints, I strongly recommend you consider data-independent pruning criteria. I'm attaching a code where the l1-norm is used to prune.  This criterion is one of the most efficient pruning criteria.
Please, take the time for understanding the code and make the necessary modifications to run in your pipeline. Currently, I have a very limited time for solving many GitHub' issues.

[l1.zip](https://github.com/arturjordao/PruningNeuralNetworks/files/5448123/l1.zip)
